### ISSUE TITLE
Getting issue while running python env_test.py (Please help !)

### ISSUE THREAD

**Issue by rshivansh** [devendrachaplot/DeepRL-Grounding#3]
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

Generating vizdoom-crash.log and killing process 30193, please wait... 29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Traceback (most recent call last):
  File "env_test.py", line 53, in <module>
    env.game_init().add_args("+vid_forcesurface 1")
  File "/new_data/gpu/shivansh/visual-grounding/DeepRL-Grounding/env.py", line 48, in game_init
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.

**Comment by rshivansh** [comment]
gets solved by
 Before game.init() add game.add_game_args("+vid_forcesurface 1").
